PACKAGE_NAME="ryzen_smu_hwmon"
PACKAGE_VERSION="@PKGVER@"

BUILT_MODULE_NAME[0]="ryzen_smu_hwmon"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hwmon"
AUTOINSTALL="yes"

MAKE[0]="make -C ${kernel_source_dir} \
M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build \
SMU_INC=$(ls -d /usr/src/ryzen_smu-*/include | head -n1) \
SMU_SYMVERS=$(ls -d /var/lib/dkms/ryzen_smu/*/*/Module.symvers | head -n1) \
modules"
